## 6. Create a 2D array and print its attributes

In [15]:
import numpy as np
a=np.array([[3,2,4],[5,3,6]])
## Its attributes are
print(f'size: {a.size}')
print(f'shape: {a.shape}')
print(f'Datatype: {a.dtype}')
print(f'Number of dimensions: {a.ndim}')
print(f'Item size: {a.itemsize} bytes')
print(f"total item size: {a.nbytes} bytes")

size: 6
shape: (2, 3)
Datatype: int32
Number of dimensions: 2
Item size: 4bytes
total item size: 24bytes


## Q. 7

In [7]:
import numpy as np
arts_student=np.array(['vishal','nishad','rahul'])
dance_st=np.array(['vikas','ritesh','deepak'])
music_st=np.array(['ritik','bob','martin'])
all_students=np.concatenate((arts_student,dance_st,music_st))
print('List of all students:',all_students)

List of all students: ['vishal' 'nishad' 'rahul' 'vikas' 'ritesh' 'deepak' 'ritik' 'bob'
 'martin']


## 8.

In [29]:
import numpy as np
marks=np.array([[45,67,23,64],[64,34,13,90],[89,87,56,78],[67,56,90,43]])
print(marks.max())
print(marks.min())
new_st=np.array([56,67,43,45])
updated_marks=np.append(marks,[new_st],axis=0)
print(updated_marks)

updated_marks=np.delete(updated_marks,2,axis=0)     ## Deleting a row
print('\n',updated_marks)

updated_marks=np.delete(updated_marks,1,axis=1)     ## Deleting a column
updated_marks


90
13
[[45 67 23 64]
 [64 34 13 90]
 [89 87 56 78]
 [67 56 90 43]
 [56 67 43 45]]

 [[45 67 23 64]
 [64 34 13 90]
 [67 56 90 43]
 [56 67 43 45]]


array([[45, 23, 64],
       [64, 13, 90],
       [67, 90, 43],
       [56, 43, 45]])

## 9. Creating a 3d array 

In [34]:
import numpy as np
arr_3d=np.random.randint(1,100,(2,4,5))
print(arr_3d)
result=arr_3d[:,1::2,0::2]
print('\nresult is : ',result)

[[[47 24 45 65 35]
  [84 56 54 94 23]
  [63 40 44 80 32]
  [66 33  6 57 70]]

 [[40 53 84 46 57]
  [62 80 74  5 58]
  [24 10 73 45 76]
  [36 16 15 61 97]]]

result is :  [[[84 54 23]
  [66  6 70]]

 [[62 74 58]
  [36 15 97]]]


In [36]:
arr=np.random.randint(1,100,(3,4))
print(arr)
col_result=arr[:,0]
col_result

[[43 82 46 48]
 [45 63  2 39]
 [69 32 38 14]]


array([43, 45, 69])

## converting 1d array into 3d array

In [41]:
arr=np.arange(24)
print(arr)

arr_3d=arr.reshape(2,4,3)
print(arr_3d)

print(arr_3d[arr_3d%2!=0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
