## Why to use NumPy
* Less Requirment of memory Size
* Much Faster than Python List
* Convenience (Syntax to write code is easy and simple)
* More Functionality

In [5]:
## Printing no from 1 to 100 using python list and numpy
import numpy as np
list_arr=[i for i in range(1,101)]

numpy_arr=np.arange(1,101)
print(list_arr)
print()
print(numpy_arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [7]:
print(numpy_arr.itemsize)
print(numpy_arr.size)
print(numpy_arr.itemsize*numpy_arr.size)

4
100
400


In [9]:
import sys
print(sys.getsizeof(1)*len(list_arr))       

2800


## Creating NumPy array

In [11]:
import numpy as np
a=[1,4,5,2,35,5]
b=np.array(a)
print(b)
print(type(b))

[ 1  4  5  2 35  5]
<class 'numpy.ndarray'>


## numpy array does not support inhomogeneous elements

In [13]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,a,65,4.5]
b=np.array(a,dtype=int)
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [14]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a,dtype=int)
print(b)

[ 3  5 65  4]


In [15]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a,dtype=str)
print(b)

['3' '5' '65' '4.5']


In [17]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a*3,dtype=int)
print(b)

[ 3  5 65  4  3  5 65  4  3  5 65  4]


## Ways to creat array
* np.ones()
* np.zeros()
* np.full()
* np.empty()

In [29]:
a=np.ones(3,4)
a

TypeError: Cannot interpret '4' as a data type

In [22]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
a=np.ones((3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
a=np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
a=np.full(3,5)
a

array([5, 5, 5])

In [30]:
a=np.full((3,5))
a

TypeError: full() missing 1 required positional argument: 'fill_value'

In [31]:
a=np.full((3,5),6)
a

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [33]:
a=np.empty(4,dtype=int)
a

array([-1390846011,  -741776599,  -483414426,  -663073136])

## Q Converting array 2d list into np array

In [34]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## all element should be 0 , but fifth element should be 5

In [35]:
a=np.zeros(10,dtype=int)
a[4]=5
print(a)

[0 0 0 0 5 0 0 0 0 0]
