## Why to use NumPy
* Less Requirment of memory Size
* Much Faster than Python List
* Convenience (Syntax to write code is easy and simple)
* More Functionality

In [5]:
## Printing no from 1 to 100 using python list and numpy
import numpy as np
list_arr=[i for i in range(1,101)]

numpy_arr=np.arange(1,101)
print(list_arr)
print()
print(numpy_arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [7]:
print(numpy_arr.itemsize)
print(numpy_arr.size)
print(numpy_arr.itemsize*numpy_arr.size)

4
100
400


In [9]:
import sys
print(sys.getsizeof(1)*len(list_arr))       

2800


## Creating NumPy array

In [11]:
import numpy as np
a=[1,4,5,2,35,5]
b=np.array(a)
print(b)
print(type(b))

[ 1  4  5  2 35  5]
<class 'numpy.ndarray'>


## numpy array does not support inhomogeneous elements

In [13]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,a,65,4.5]
b=np.array(a,dtype=int)
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [14]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a,dtype=int)
print(b)

[ 3  5 65  4]


In [15]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a,dtype=str)
print(b)

['3' '5' '65' '4.5']


In [17]:
## Numpy array is homogeneous , it does not support multiple datatype
a=[3,5,65,4.5]
b=np.array(a*3,dtype=int)
print(b)

[ 3  5 65  4  3  5 65  4  3  5 65  4]


## Ways to creat array
* np.ones()
* np.zeros()
* np.full()
* np.empty()

In [29]:
a=np.ones(3,4)
a

TypeError: Cannot interpret '4' as a data type

In [22]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
a=np.ones((3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
a=np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
a=np.full(3,5)
a

array([5, 5, 5])

In [30]:
a=np.full((3,5))
a

TypeError: full() missing 1 required positional argument: 'fill_value'

In [31]:
a=np.full((3,5),6)
a

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [33]:
a=np.empty(4,dtype=int)
a

array([-1390846011,  -741776599,  -483414426,  -663073136])

## Q Converting array 2d list into np array

In [34]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## all element should be 0 , but fifth element should be 5

In [35]:
a=np.zeros(10,dtype=int)
a[4]=5
print(a)

[0 0 0 0 5 0 0 0 0 0]


## NumPy Functions

In [44]:
a=np.arange(3)
a

array([0, 1, 2])

In [45]:
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
a=np.linspace(2,20)   # it gives by default 50 samples
a

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [50]:
a=np.linspace(2,20, 15 ,dtype=int,endpoint=False)  
a

array([ 2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18])

In [36]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
a=np.random.rand(3)
a

array([0.23104796, 0.18487061, 0.69473356])

In [42]:
a=np.random.rand(10)*5
a

array([0.58619457, 1.06525869, 1.19224797, 3.57087047, 2.17426156,
       3.51860327, 2.89799856, 3.49763082, 1.59462814, 4.22013304])

## Q. Random int array of size 4*4

In [52]:
a=np.random.randint(10,size=(4,4))
a

array([[2, 3, 0, 0],
       [4, 3, 8, 7],
       [1, 6, 4, 6],
       [8, 8, 8, 9]])

In [53]:
a=np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [55]:
a=np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [61]:
a=np.linspace(0,5,9+1)
a=np.round(a,2)
a

array([0.  , 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.  ])

## Indexing and Slicing

In [62]:
a=[2,3,5,6]
b=np.array(a)
b

array([2, 3, 5, 6])

In [63]:
print(b[3])

6


In [64]:
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
b=np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
print(b[0:2,1:3])

[[2 3]
 [6 7]]


In [66]:
print(b[2,2])

11


In [67]:
print(b[:4,0])

[ 1  5  9 13]


In [68]:
print(b[2:4,3])

[12 16]


## Finding Indices of elements

In [2]:
import numpy as np
a=np.array([2,4,5,6,54,6,45])
ind=np.where(a==6)     ## np.where print index no. of element
ind

(array([3, 5], dtype=int64),)

## Q. Printing Non - Zero Elements

In [3]:
a=np.array([1,2,0,0,4,0])
ind=np.where(a!=0)
ind

(array([0, 1, 4], dtype=int64),)

## . Printing the index of elements which are multiple of three

In [6]:
a=np.array([2,4,5,3,6,1,15,9,18])
ind=np.where(a%3==0)
ind

(array([3, 4, 6, 7, 8], dtype=int64),)

## Q REplacing the ODD no. with -1

In [7]:
a=np.array([1,54,3,6,4,645,3,6,47])
ind=np.where(a%2!=0)
a[ind]=-1
a

array([-1, 54, -1,  6,  4, -1, -1,  6, -1])

## Q. Printing Age of students whose height is more than 155cm

In [2]:
import numpy as np
age=np.array([19,18,23,21,20,17,25,19,24,26])
ht=np.array([147,157,123,156,170,172,180,127,145,155])
ind=np.where(ht>=155)
print(age[ind],ht[ind])

[18 21 20 17 25 26] [157 156 170 172 180 155]


## Indexing for 2D arrays

In [11]:
a=np.random.randint(1,30,(5,6))
a
bool_arr=a>20
print(a)
bool_arr

[[20  5 23 15 25 16]
 [25 14 16  8 26  5]
 [ 5 24  4  1  5  8]
 [11 24 22 17  6 17]
 [20  2 11  7  8 15]]


array([[False, False,  True, False,  True, False],
       [ True, False, False, False,  True, False],
       [False,  True, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False]])

In [12]:
a[bool_arr]=100
a

array([[ 20,   5, 100,  15, 100,  16],
       [100,  14,  16,   8, 100,   5],
       [  5, 100,   4,   1,   5,   8],
       [ 11, 100, 100,  17,   6,  17],
       [ 20,   2,  11,   7,   8,  15]])

## Q Sort the 2D array by 2nd column i.e 1 index

In [14]:
a=np.random.randint(1,50,(4,5))
print(a)
sorted_arr=a[a[:,1].argsort()]   ### .argsort()
sorted_arr

[[42  5 16 38  5]
 [28 38 29 16 17]
 [41 44 43 41 47]
 [ 7 32 38 26  5]]


array([[42,  5, 16, 38,  5],
       [ 7, 32, 38, 26,  5],
       [28, 38, 29, 16, 17],
       [41, 44, 43, 41, 47]])

## Q. Broadcasting and mathematical operations

In [15]:
a=np.random.randint(1,30,(3,3))
b=np.random.randint(1,20,(3,3))
print(a)
print(b)

[[22  8 23]
 [24  2 23]
 [26 20 17]]
[[13  6 18]
 [ 3  2  6]
 [ 5 10 15]]


In [16]:
ans=a-b
ans

array([[ 9,  2,  5],
       [21,  0, 17],
       [21, 10,  2]])

* Broadcasting

In [17]:
c=np.random.randint(1,20,(3))
c

array([ 4,  9, 19])

In [19]:
ans=a-c    ## this is how bradcasting work
ans

array([[18, -1,  4],
       [20, -7,  4],
       [22, 11, -2]])

## using transpose function

In [20]:
d=np.random.randint(1,10,(2,3))
e=np.random.randint(1,10,(3,2))
print(d)
print(e)

[[9 2 6]
 [1 1 1]]
[[1 4]
 [7 4]
 [9 1]]


In [21]:
ans=d-e
ans

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [22]:
e=np.transpose(e)
print(e)
ans=d-e
ans

[[1 7 9]
 [4 4 1]]


array([[ 8, -5, -3],
       [-3, -3,  0]])

## NumPy Example

In [33]:
import numpy as np
import csv
file_obj=open('year2017.csv')
file_data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]
for row in file_data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])

np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
killed_wounded=np_killed+np_wounded

print(sum(killed_wounded))

## for india
np_country=np.array(country)
bool_arr= np_country=='India'
print(killed_wounded[bool_arr])
print(np.sum(killed_wounded[bool_arr]))

51372.0
[ 0.  1.  4.  1.  1.  0.  2.  2.  0.  1.  2.  2.  1.  0.  1.  4.  0.  0.
  0.  0.  0.  0.  1.  4.  1.  2.  1.  0.  5.  1.  0.  0.  1.  1.  0.  0.
  7.  0.  1.  0.  0.  0.  0.  0.  4.  0. 95.  0.  2.  0.  1.  0.  1.  0.
  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  0.
  1.  1. 18.  2. 13.  1.  0.  3.  0.  1.  0.  0.  0.  1.  1. 10.  0.  0.
  1.  1.  0.  1.  0.  0.  1.  1.  0.  0.  2.  1.  0.  4.  0.  0.  0.  0.
  0.  1.  0.  5.  2.  0.  0.  0.  2.  1.  2.  0.  0.  0.  0.  1.  1.  4.
  1.  0.  0.  1.  1.  1.  9.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.
  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  1.  0.  0.  8.  0.  0.  0.  0.
  0.  2.  0.  0.  0.  0.  1.  0.  3.  0.  0.  0.  0.  0.  0. 10.  1.  1.
  0.  0.  0.  5.  1.  0.  2.  0.  1.  1. 16.  0.  0.  1.  0.  1.  1.  1.
  1.  0.  2.  0.  0.  1.  2.  0.  0.  0.  0.  1.  0.  0.  0.  1.  1.  1.
  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  3.  0.  0.  0.  0.
  1.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1

## Q. Killed In USA

In [42]:
import numpy as np
import csv
file_obj=open('terrorismData.csv',encoding='utf-8')
file_data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
country=[]
for row in file_data:
    killed.append(row['Killed'])
    country.append(row['Country'])
np_killed=np.array(killed)

np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)

np_country=np.array(country)
bool_arr=np_country=='United States'
print(np_killed[bool_arr])

print(int(np.sum(np_killed[bool_arr])))
    

[0. 0. 0. ... 0. 0. 1.]
3771
